### ISSUE TITLE
Zero-initialization in CFixedString::with_limit

### ISSUE THREAD

**Issue by dtolnay** [Diggsey/c_fixed_string-rs#1]
The documentation says:

> Construct an empty string with the specified limit. The buffer is entirely zero-initialized.

I would expect it set just the first byte of the buffer to 0, or at least not commit to the guarantee that the whole buffer is entirely zero-initialized even if that is what the implementation does currently.

**Comment by Diggsey** [comment]
I very nearly did that, but for a couple of things:
1) For safety, the buffer *must* be initialised to *something* as reading uninitialised memory is unsafe.
2) Initialising to zero is strictly more useful, as you can copy data in without having to explicitly null terminate it.

For those reasons, I figured it would be better to just keep it as a feature, since there's no possible optimisation opportunities anyway.
